name: Lint and SAST
description: Run linters and static application security testing.
runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 bandit

    - name: Run Flake8 Lint
      run: flake8 .

    - name: Run Bandit SAST
      run: bandit -r .
