apiVersion: apps/v1
kind: Deployment
metadata:
  name: pspdfkit-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pspdfkit-app
  template:
    metadata:
      labels:
        app: pspdfkit-app
    spec:
      containers:
        - name: pspdfkit-app
          image: behaqosimi/nice-test-task:47594b75f26957f458b7d1f1964e90a1229db7ad
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
