name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-and-sast:
    name: Lint and SAST
    uses: ./.github/workflows-reusable/lint-and-sast.yml@main

  test-and-build:
    name: Test and Build
    needs: lint-and-sast
    uses: ./.github/workflows-reusable/test-and-build.yml@main
