name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-and-sast:
    name: Lint and SAST
    uses: ./.github/workflows/lint-and-sast.yml

  test-and-build:
    name: Test and Build
    uses: ./.github/workflows/test-and-build.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
