name: Lint and SAST

on:
  workflow_call:

jobs:
  lint-and-sast:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir flake8 bandit

      - name: Run Flake8 Lint
        run: flake8 .

      - name: Run Bandit SAST
        run: bandit -r . --exit-zero
