name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  lint-and-sast:
    name: Lint and SAST
    uses: ./.github/workflows/lint-and-sast.yml

  test-and-build:
    name: Test and Build
    needs: lint-and-sast
    uses: ./.github/workflows/test-and-build.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  release:
    name: Release
    needs: [lint-and-sast, test-and-build]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Archive Code
        run: zip -r code.zip ./*

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: 'code-artifact'
          path: './code.zip'
          if-no-files-found: 'warn'
          retention-days: 1
