name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  lint-and-sast:
    name: Lint and SAST
    uses: ./.github/workflows/lint-and-sast.yml

  test-and-build:
    name: Test and Build
    needs: lint-and-sast
    uses: ./.github/workflows/test-and-build.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Archive Code
        run: zip -r code.zip ./*

      - name: Upload Release Asset
        uses: PeerXu/upload-asset@v1
        with:
          file: ./code.zip
          os: linux
          suffix: .zip
